### ISSUE TITLE
Tìm hiểu cụm Kubernetes và ứng dụng demo

### ISSUE THREAD

**Issue by khoa-nguyen-oss4115** [khoa-nguyen-oss4115/Project_CloudComputing#1]
Tìm hiểu Kubernetes, cách sử dụng và chạy demo hadoop nhiều node trên Kubernetes.

**Comment by khoa-nguyen-oss4115** [comment]
[Kubernets.pdf](https://github.com/khoa-nguyen-oss4115/Project_CloudComputing/files/6377104/Kubernets.pdf)

**Comment by NguyenQuangHung911** [comment]
[KubernetesComponents.pdf](https://github.com/khoa-nguyen-oss4115/Project_CloudComputing/files/6528562/KubernetesComponents.pdf)
Tìm hiểu các thành phần của Kubernetes
